.github/workflows/npm-publish.yaml

Towards https://github.com/RequestNetwork/docs.request.network/issues/27
* Remove `--dry-run`
* Trigger publish on push to master

Remove dry run

---

.github/workflows/npm-publish.yaml
CONTRIBUTING.md
README.md

* Add CONTRIBUTING.md
* Update README.md
* Clarify release action step name

chore: add CONTRIBUTING.md, Update README.md

---

packages/create-invoice-form/src/lib/create-invoice-form.svelte
packages/invoice-dashboard/src/lib/dashboard/invoice-view.svelte
packages/invoice-dashboard/src/lib/view-requests.svelte
packages/shared/src/lib/ui/modal.svelte
packages/shared/src/lib/ui/status.svelte

**Description**
We didn't use colors from the config, now it's added where the colors should be dynamic

fix: Change colors to config.colors

---

README.md
packages/add-stakeholder/README.md
packages/create-invoice-form/README.md
packages/invoice-dashboard/README.md
packages/shared/README.md

* Update READMEs in preparation for NPM release

fix: READMEs

---

.github/workflows/npm-publish.yaml
packages/add-stakeholder/package.json
packages/create-invoice-form/package.json
packages/invoice-dashboard/package.json
packages/shared/package.json

* Automate the NPM release for new packages
* @requestnetwork/create-invoice-form
* @requestnetwork/invoice-dashboard
* @requestnetwork/shared
* Increment version numbers

feat: release

---

package-lock.json
packages/create-invoice-form/src/lib/create-invoice-form.svelte
packages/create-invoice-form/src/lib/invoice/form.svelte
packages/invoice-dashboard/src/lib/dashboard/invoice-view.svelte
packages/invoice-dashboard/src/lib/view-requests.svelte
packages/invoice-dashboard/src/utils/formatAddress.ts
packages/shared/package.json
packages/shared/src/lib/index.ts
packages/shared/src/lib/ui/input.svelte
packages/shared/src/lib/utils/checkEthAddress.ts

* Fix bug where ethereum address validation failed when it should have succeeded
* Trigger address validation when user clicks outside of the input field.
* Fix bug where invoice form was reset after an error occurred. 
* Only reset the form when the user clicks "Create New Invoice" - This way, when errors occur, the user does not need to re-fill the form.
* Fix data object - "matic" instead of "polygon"
* Fix bug where certain addresses were parsed incorrectly causing the dashboard to show the loading skeleton forever.
* Reverse default sort behavior - show most recent invoices first
* Fix bug where invoices with more than 3 line items would show messed up styling after clicking "view more"

fix: many prod errors

---

packages/create-invoice-form/src/lib/create-invoice-form.svelte
packages/create-invoice-form/src/lib/invoice/form.svelte

- Adds missing check for disabling create invoice button when invalid wallet addresses are provided.

fix: disable create invoice button if invalid addresses are provided

---

packages/create-invoice-form/README.md
packages/invoice-dashboard/README.md

- Update readme to include warning a for NextJS 14.x to disable swcMinify
- Replace permalinks with `main` branch links
- Add spacing to markdown tables

chore: update docs with swc warning

---

packages/create-invoice-form/src/lib/create-invoice-form.svelte
packages/create-invoice-form/src/lib/invoice/form-view.svelte
packages/create-invoice-form/src/lib/invoice/form.svelte

* fix: bug where the "From" input fields overlapped with the Issue Date and Due Date fields.
* fix: Improve responsiveness by moving the Invoice View under the Invoice Form on screens narrower than 1024 px.

fix: added media queries for smaller laptops

---

packages/invoice-dashboard/package.json

- updated to `0.3.1` because we changed the version of the `shared` package

chore: increment invoice-dashboard version

---

packages/shared/package.json
packages/shared/src/lib/ui/powered-by.svelte

- updated the powered-by component when clicked it goes to RN homepage
- updated the package version to `0.4.0`

feat: added link around the powered by

---

package-lock.json
packages/create-invoice-form/package.json
packages/create-invoice-form/src/lib/create-invoice-form.svelte
packages/create-invoice-form/src/lib/invoice/form.svelte
packages/invoice-dashboard/package.json
packages/invoice-dashboard/src/lib/view-requests.svelte

- updated the package versions
- updated the shared package version
- updated the props to use the `activeConfig` variable (`Error: .colors not found` is fixed)
- fixed the header table styling
- fixed the remove item styling

fix: Better styling and .colors error fix

---

package-lock.json
packages/create-invoice-form/package.json
packages/create-invoice-form/src/lib/invoice/form-view.svelte
packages/shared/src/lib/utils/formatDate.ts

- fixed the date pickers for issued and due date
- updated package version to `0.5.0`

fix: Issued and due date fix

---

packages/create-invoice-form/src/lib/create-invoice-form.svelte
packages/create-invoice-form/src/lib/invoice/form-view.svelte
packages/create-invoice-form/src/lib/invoice/form.svelte
packages/invoice-dashboard/src/lib/dashboard/drawer.svelte
packages/invoice-dashboard/src/lib/dashboard/invoice-view.svelte
packages/invoice-dashboard/src/lib/view-requests.svelte

- added responsive for the dashboard
- added responsive for invoice form
Invoice Dashboard:
https://github.com/RequestNetwork/web-components/assets/73234992/fb1af999-7ffe-46cf-8c4b-9aee8c043c0d
Create Invoice:
https://github.com/RequestNetwork/web-components/assets/73234992/63c971ee-0637-494d-a8ac-d0497a57451e

feat: added responsive design to dashboard and form

---

packages/add-stakeholder/package.json

Revert add-stakeholder package to its correct version

fix: revert add stakehold to correct version

---

.github/workflows/npm-publish.yaml

Fixes #29 
* Configure npm registry

fix: publish

---

.github/workflows/npm-publish.yaml

Fixes #29 
* fix: npm registry URL to use HTTPS

fix: npm registry URL to use HTTPS

---

packages/create-invoice-form/package.json
packages/invoice-dashboard/package.json
packages/payment-widget/package.json

Increase packages npm version in order to release.

chore: increase package size for release

---

.github/workflows/npm-publish.yaml
README.md
packages/payment-widget/package.json

Fixes #29 
Changes:
- Add payment widget to release process

chore: add payment-widget to release process

---

.github/workflows/npm-publish.yaml

chore: remove npm publish dry run

---

packages/payment-widget/package.json

Fixes #29
Changes:
- Bump version so it releases a new version.

chore: bump the version

---

README.md
package-lock.json
packages/invoice-dashboard/src/lib/view-requests.svelte
packages/invoice-dashboard/src/utils/capitalize.ts
packages/invoice-dashboard/src/utils/index.ts

Fixes #97
Changes:
- Add handler to all request status
- Add fix for npm link issue to readme

feat: handle all request status

---

packages/create-invoice-form/src/lib/invoice/form.svelte
shared/components/button.svelte

Reverts RequestNetwork/web-components#198

Revert "Updated form to use "Add Recipient Address""

---

package-lock.json
packages/create-invoice-form/package.json
packages/invoice-dashboard/package.json

Release https://github.com/RequestNetwork/web-components/pull/214 so we can release Request Invoicing 0.11.0

chore: release create-request-form@0.11.1 and invoice-dashboard@0.10.1

---

packages/create-invoice-form/package.json
packages/create-invoice-form/src/lib/react/CreateInvoiceForm.d.ts
packages/invoice-dashboard/package.json
packages/invoice-dashboard/src/lib/react/InvoiceDashboard.d.ts

- Currencies prop should been removed from required props
- Make currency prop optional in the types files
- Patch version bump

fix: Removed required currency prop from web-components
